# Generated by Django 3.0.5 on 2020-07-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='recipe.RecipeItem'),
        ),
    ]
